include ../Makefile.tests_common

USEPKG += nrf_modem

USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps
USEMODULE += ztimer_msec
USEMODULE += ztimer_sec
USEMODULE += ztimer


CFLAGS += -DDEBUG_VERBOSE_ASSERT

include $(RIOTBASE)/Makefile.include
