ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
  USEMODULE += hts221
  USEMODULE += lis3mdl
  USEMODULE += lps22hb
  USEMODULE += lsm6dsl
endif

USEMODULE += stdio_cdc_acm

# USB device vendor and product ID
DEFAULT_VID = 1209
DEFAULT_PID = 7D00
USB_VID ?= $(DEFAULT_VID)
USB_PID ?= $(DEFAULT_PID)

CFLAGS += -DCONFIG_USB_VID=0x$(USB_VID) -DCONFIG_USB_PID=0x$(USB_PID)
