
ROM_LEN ?= 0x100000
RAM_LEN ?= 0x40000

FLASHFILE ?= $(BINFILE)

PROGRAMMER ?= jlink
JLINK_DEVICE = NRF9160_XXAA

include $(RIOTCPU)/nrf5x_common/Makefile.include
include $(RIOTMAKE)/arch/cortexm.inc.mk

ifneq (,$(filter nrfxlib_nrf_modem,$(USEMODULE)))
  include $(RIOTMAKE)/tools/nrf_modem_fw.inc.mk
endif
