INCLUDES += -I$(BUILD_DIR)/pkg/nrf_modem/nrf_modem/include
INCLUDES += -I$(RIOTPKG)/nrf_modem/contrib

LINKFLAGS += -L$(RIOTBASE)/build/pkg/nrf_modem/nrf_modem/lib/cortex-m33/soft-float
LINKFLAGS += -lmodem

DIRS += $(RIOTPKG)/nrf_modem/contrib


ifneq (,$(filter nrf_modem_netdev,$(USEMODULE)))
  DIRS += $(RIOTBASE)/pkg/nrf_modem/contrib/netdev
endif